### ISSUE TITLE
Build ERROR in : Cannot determine the module for class ChatComponent

### ISSUE THREAD

**Issue by dandelarge** [kingsley-einstein/devicity-client#12]
Building production code, build breaks due to a missing declaration.

`ERROR in : Cannot determine the module for class ChatComponent in /devicity-client/src/app/gui/chat/chat.component.ts! Add ChatComponent to the NgModule to fix it.
Cannot determine the module for class LoginComponent in /devicity-client/src/app/gui/login/login.component.ts! Add LoginComponent to the NgModule to fix it.`

**Comment by karthikrp** [comment]
Seems to be working. It ran successfully with 'npm start'.

**Comment by dandelarge** [comment]
This is not about running the server, but actual building of the production code. Run the following to replicate:

`ng build --prod --aot`

**Comment by karthikrp** [comment]
Closed via PR #15
